spring.application.name=OAuth2OpenIDConnectavecKeycloak
server.port=8081
# DOIT être exactement cette URL
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/elearning-realm